// app/(auth)/login/page.tsx
// PIN-based login page

'use client'

import { useState, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { AlertCircle, CheckCircle, Loader2, Eye, EyeOff } from 'lucide-react'
import { useAuthStore } from '@/stores/authStore'
import { cn } from '@/lib/utils'

function LoginForm() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const redirect = searchParams.get('redirect') || '/'
  const { setUser, setLoading } = useAuthStore()
  
  const [pin, setPin] = useState('')
  const [showPin, setShowPin] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [attempts, setAttempts] = useState(0)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (pin.length !== 4 || !/^\d{4}$/.test(pin)) {
      setError('PIN harus 4 digit angka')
      return
    }

    setIsLoading(true)
    setError(null)

    try {
      const response = await fetch('/api/auth/pin', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ pin }),
      })

      const data = await response.json()

      if (!response.ok) {
        setAttempts(prev => prev + 1)
        if (data.locked) {
          setError('Terlalu banyak percobaan. Coba lagi nanti.')
        } else {
          setError(data.error || 'PIN salah')
        }
        return
      }

      // Normalize DB shape (`full_name`) into the frontend `User` shape
      // (`name`). Without this, every consumer reading `user.name` (the
      // sidebar avatar, the topbar avatar, etc.) silently gets `undefined`,
      // which then becomes the literal string "undefined" in query params
      // — visible as /api/avatar?name=undefined 404 in the console.
      const { full_name, division_id, avatar_url, is_active, ...rest } = data.user
      const normalizedUser = {
        ...rest,
        name: full_name,
        divisionId: division_id,
        avatarUrl: avatar_url,
        isActive: is_active,
      }
      setUser(normalizedUser as any)
            // Force full reload so server-side middleware/RSC reads fresh cookies
            // (router.push is client-only and does not re-evaluate middleware)
            window.location.href = redirect
    } catch {
      setError('Terjadi kesalahan. Silakan coba lagi.')
    } finally {
      setIsLoading(false)
    }
  }

  // Demo users — PINs are unique per user, generated by the seed
  // script. The list here is intentionally informational; do NOT publish
  // these PINs in a production build.
  const demoUsers = [
    { name: 'Pak Ardian (Owner)', pin: '1607', role: 'owner' },
    { name: 'Bu Nisya (Legal)', pin: '4475', role: 'pic_divisi' },
    { name: 'Mada (Kepala Kantor)', pin: '0327', role: 'kepala_kantor' },
    { name: 'Riza (Marketing)', pin: '5991', role: 'staff' },
    { name: 'Yudi (Mkt+Maintenance)', pin: '7927', role: 'staff' },
    { name: 'Amir (Mkt+Konstruksi)', pin: '6478', role: 'staff' },
    { name: 'Rizal (Kepala Proyek)', pin: '4410', role: 'pic_divisi' },
    { name: 'Novita (Keuangan)', pin: '5528', role: 'staff' },
    { name: 'Sinta (Purchasing)', pin: '8143', role: 'staff' },
    { name: 'Reni (Ketua Media)', pin: '5008', role: 'pic_divisi' },
    { name: 'Rifki (Kreatif)', pin: '1532', role: 'staff' },
    { name: 'Reta (Penulis)', pin: '5182', role: 'staff' },
  ]

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--color-surface-0)] p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center h-16 w-16 rounded-xl bg-[var(--color-brand-500)] mb-4">
            <CheckCircle className="h-10 w-10 text-primary-foreground" />
          </div>
          <h1 className="font-heading text-3xl font-bold text-[var(--color-text-primary)]">Syahfalah Dashboard</h1>
          <p className="text-[var(--color-text-secondary)] mt-2">
            PT Syahfalah Global · PT Lembayung Wanantara Padha · Grup Majang Mejeng
          </p>
        </div>

        <Card className="shadow-xl">
          <CardHeader className="text-center">
            <CardTitle className="text-xl">Masuk ke Dashboard</CardTitle>
            <CardDescription>Masukkan 4-digit PIN Anda</CardDescription>
          </CardHeader>
          <CardContent>
            {error && (
              <div className="mb-4 p-3 rounded-lg bg-[var(--color-danger)]/10 border border-[var(--color-danger)]/20 text-[var(--color-danger)] text-sm flex items-center gap-2">
                <AlertCircle className="h-4 w-4 flex-shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="relative">
                <Label htmlFor="pin" className="sr-only">PIN</Label>
                <Input
                  id="pin"
                  type={showPin ? 'text' : 'password'}
                  inputMode="numeric"
                  pattern="[0-9]*"
                  maxLength={4}
                  value={pin}
                  onChange={(e) => {
                    const value = e.target.value.replace(/\D/g, '').slice(0, 4)
                    setPin(value)
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && pin.length === 4) {
                      handleSubmit(e as unknown as React.FormEvent)
                    }
                  }}
                  placeholder="●●●●"
                  className="text-center text-2xl tracking-widest h-14"
                  autoComplete="off"
                  autoFocus
                  disabled={isLoading}
                />
                <button
                  type="button"
                  onClick={() => setShowPin(!showPin)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]"
                  aria-label={showPin ? 'Sembunyikan PIN' : 'Tampilkan PIN'}
                >
                  {showPin ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}
                </button>
              </div>

              <Button type="submit" className="w-full h-12 text-lg" disabled={isLoading || pin.length !== 4}>
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Memverifikasi...
                  </>
                ) : (
                  'Masuk'
                )}
              </Button>
            </form>

            <div className="mt-6 p-4 rounded-lg bg-[var(--color-surface-2)]/50 border border-[var(--color-border-default)]">
              <p className="text-xs text-[var(--color-text-secondary)] text-center mb-3">Akun Demo (PIN lihat di footer — bukan untuk produksi)</p>
              <div className="grid grid-cols-2 gap-2 max-h-48 overflow-y-auto scrollbar-thin">
                {demoUsers.map((user, i) => (
                  <button
                    key={i}
                    type="button"
                    onClick={() => setPin(user.pin)}
                    className="text-left p-2 rounded hover:bg-[var(--color-surface-0)]/50 transition-colors text-sm"
                  >
                    <span className="font-medium text-[var(--color-text-primary)]">{user.name}</span>
                    <span className="text-xs text-[var(--color-text-secondary)] block">Role: {user.role.replace('_', ' ')}</span>
                  </button>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>

        <p className="text-center text-xs text-[var(--color-text-secondary)] mt-6">
          Internal use only — PT Syahfalah Global · Dibuat oleh MADA
        </p>
      </div>
    </div>
  )
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>}>
      <LoginForm />
    </Suspense>
  )
}